server:
  port: 8081
spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: kcc
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kcc.restful.bean

#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true



#logging:
#    level:
#        org.springframework: DEBUG